
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
```


```{r}
# Descriptive table

dig.df<-read_csv("DIG.csv",
                 col_types = "nnnnnnnnnnnnnnnnn")

dig.df<- select(dig.df, "ID", "TRTMT", "AGE", "SEX", "BMI", "CREAT",
         "DIABP", "SYSBP", "HYPERTEN", "CVD", "WHF", "HOSP", 
         "HOSPDAYS", "DEATH", "DEATHDAY")
dig.df <- na.omit(dig.df)

colnames(dig.df)[1] <- "ID" 

dig.df <- dig.df
#TRTMT
dig.df$TRTMT <- as.numeric(as.character(dig.df$TRTMT))
dig.df$TRTMT<- factor(dig.df$TRTMT,
                     levels = c(0,1),
                     labels = c("placebo", "Digoxin"))

#SEX
dig.df$SEX <- as.numeric(as.character(dig.df$SEX))
dig.df$SEX<- factor(dig.df$SEX,
                     levels = c(1,2),
                     labels = c("Male", "Female")) 

dig.df$CVD <- factor(dig.df$CVD ,
                      levels = c(0 , 1), 
                      labels = c("No", "Yes"))
# WHF
dig.df$WHF <- factor(dig.df$WHF,
                     levels  = c(0,1), 
                      labels= c("Not Worsening HF", "Worsening HF"))

dig.df$HOSP <- factor(dig.df$HOSP,
                      levels  = c(0,1), 
                      labels= c("Not Hospitalized", "Hospitalized"))
#HYPERTEN
dig.df$HYPERTEN <- as.numeric(as.character(dig.df$HYPERTEN))
dig.df$HYPERTEN<- factor(dig.df$HYPERTEN,
                     levels = c(0,1),
                     labels = c("Not Hypertensive", "Hypertensive")) 

#DEATH
dig.df$DEATH <- as.numeric(as.character(dig.df$DEATH))
dig.df$DEATH<- factor(dig.df$DEATH,
                     levels = c(0,1),
                     labels = c("Alive", "Death")) 
names(dig.df)
dig.df <- dig.df%>%
  mutate(Month = round(DEATHDAY/30, ))
dig.df
```
 
```{r}
#Plot 2 
#Hospitalization due to CVD
dig.df %>% ggplot(aes(x=CVD, fill = factor(TRTMT))) + 
  labs(x="Treatment",
       title="Hospitalisation between treatment groups") +
  scale_fill_manual(values = c("#669933", "#FFCC66"),
    name = "Treatment group") +
  geom_bar(alpha=0.7, position="fill") +
  labs(x="Hospitalization for CVD",title = "Hospitalization in due to CVD in each")
```


```{r}
# Plot 3
# Hospitalisation due to WHF
dig.df %>% ggplot(aes(x=WHF, fill = factor(TRTMT))) + 
  labs(x="Treatment",
       title="Hospitalisation between treatment groups") +
  scale_fill_manual(values = c("#f09c1b", "#4f78b4"),
    name = "Treatment group") +
  geom_bar(alpha=0.7, position="fill") +
  labs(x="Hospitalization for CVD",title = "Hospitalization due to WHF in treatment groups")

```


```{r}

#Plot 4
# Month of Death in Treatment Groups
Month_summary<- dig.df%>%
  summarise(
    count =n(),
    Min = min(Month, na.rm = T),
    Q1 = quantile(Month,0.25, na.rm = T),
    Median = median(Month, na.rm = T),
    Average = mean(Month, na.rm = T),
    Q3 = quantile(Month,0.75, na.rm = T),
    Max = max(Month, na.rm= T),
    SD = sd(Month, na.rm = T),
  )
Month_summary
    
# Graphical summary
dig.df
ggplot(dig.df, 
       aes(x = Month, fill = TRTMT, y = after_stat(density)) ) + 
  geom_histogram() +
  geom_density(alpha = 0.8) +
  labs(title = "Distribution of summary statstics DIG participants in each treatment group", 
       subtitle = "Histogram for Month of Death and Treatment Group",
       caption = "\n: Distribution of month of death of patients by
              in each treatment arms",
       x = "Month", 
       y= "Frequency")

```

```{r}
#sub-tab of death
#Death due to CVD
library(tidyr)
library(plotly)
             
cvd_mortality_by_treatment<- dig.df%>%
  group_by(TRTMT, CVD)%>%
  summarise(
    Total = n(),
    Deaths = sum(DEATH== "Death", na.rm = T),
    Mortality_Rate = Deaths/Total
  )
cvd_mortality_by_treatment


cvd_plot_strat<- ggplot(cvd_mortality_by_treatment,
                        aes(x = CVD, y=Mortality_Rate , fill = TRTMT))+
  #using position dodge to place each treatment groups side by side
  geom_col(position = position_dodge(width = 0.8), color = "lightblue")+
   scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values = c("#8970b3", "#2d7e74"))+
  labs(
    title = "Mortality rate by CVD status in each treatment group ",
    x = "Cardiovascular Disease(CVD) status",
    y = "Mortality Rate(%)",
    fill = "Treatment Group",
    caption = "\n Mortality rate by among patients with and without CVD in each treatment group")


cvd_plot_strat
ggplotly(cvd_plot_strat)
```

```{r}
#subtab two
#Death due to WHF
library(tidyr)
             
whf_mortality_by_treatment<- dig.df%>%
  group_by(TRTMT, WHF)%>%
  summarise(
    Total = n(),
    Deaths = sum(DEATH== "Death", na.rm = T),
    Mortality_Rate = Deaths/Total
  )
whf_mortality_by_treatment
whf_plot_strat<- ggplot(whf_mortality_by_treatment,
                        aes(x = WHF, y=Mortality_Rate , fill = TRTMT))+
  #using position dodge to place each treatment groups side by side
  geom_col(position = position_dodge(width = 0.8), color = "lightblue")+
   scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values = c("#8970b3", "#e74"))+
  labs(
    title = "Mortality rate by Worsening Heart Failure in each treatment group ",
    x = "Worsening Heart Failure(WHF) status",
    y = "Mortality Rate(%)",
    fill = "Treatment Group",
    caption = "\n Mortality rate by among patients with and without Worsening Heart Failure in each treatment group")
whf_plot_strat

ggplotly(whf_plot_strat)
```


```{r}
#Plot 6
#Survival 
library(survival)
library(survminer)
library(plotly)

# Fitting the survival model(Kaplan-Meier Method)
survival_function <- survfit(Surv(dig.df$Month,
                                  dig.df$DEATH == "Death")~1, data = dig.df, na.action = na.omit, conf.int = TRUE) 
str(survival_function)
summary(survival_function)
plot(survival_function)

base_P<- ggsurvplot(
  survival_function, data = dig.df,
  title = "Overall Patient survival curve( Kaplan-Meier)",
  xlab = "Time(Approximate Months)",
  ylab = "survival Probability",
  risk.table = TRUE,
  conf.int = TRUE,
  ggtheme = theme_bw()
)


p_interactive <- ggplotly(base_P$plot)
p_interactive
```

```{r}
#Plot5
#Scatter
clean_dig.df<- dig.df%>% # omitting any missed BP measurement from the dataset
  filter(
    !is.na(SYSBP),
    !is.na(DIABP),
    !is.na(TRTMT),
    !is.na(HYPERTEN),
  )
clean_dig.df

# Animated graphical presentation 
clean_dig.df %>%
  plot_ly(
    x = ~SYSBP , 
    y = ~DIABP , 
    size = ~BMI, 
    color = ~TRTMT, 
    colors = c('gold', 'black'),
    frame = ~ Month, 
    text = ~ID, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  ) %>% 
  layout(
  xaxis = list(
    type = "log"
  )
  ) %>%
  animation_opts(frame = 1000, transition = 250, redraw = FALSE)

```

